project:
  type: website
  output-dir: docs

website:
  title: "Multivariate Analysis by R"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Methods
        menu:
          - text: "Canonical Correlation Analysis (CCA)"
            file: cca.qmd
          - text: "Cluster Analysis"
            file: cluster.qmd
          - text: "Discriminant Analysis"
            file: discriminant.qmd
          - text: "Factor Analysis of Mixed Data (FAMD)"
            file: famd.qmd
          - text: "Logistic Regression"
            file: logistic.qmd
          - text: "Multidimensional Scaling (MDS)"
            file: mds.qmd
          - text: "Multinomial / Ordinal Logistic Regression"
            file: multinomial.qmd
          - text: "Multiple Regression"
            file: multiple_regression.qmd
          - text: "Multivariate Analysis of Variance (MANOVA)"
            file: manova.qmd
          - text: "Principal Component Analysis (PCA)"
            file: pca.qmd
          - text: "Random Forest / Gradient Boosting"
            file: random_forest.qmd
          - text: "Support Vector Machines (SVM)"
            file: svm.qmd
  page-footer:
    center: "© 2025 Your Name"

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    code-fold: show
