name: Render Rmd to docs (branch deploy)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # cho phép commit ngược về repo

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install packages
        run: |
          Rscript -e 'install.packages(c(
            "rmarkdown","MASS","FactoMineR","factoextra",
            "nnet","tidymodels","ranger","xgboost","e1071"
          ))'

      - name: Render ALL .Rmd into docs/
        run: |
          Rscript -e 'dir.create("docs", showWarnings = FALSE);
                      rmds <- list.files(pattern="\\.Rmd$", ignore.case=TRUE);
                      for (f in rmds) {
                        out <- file.path("docs", sub("\\\\.Rmd$", ".html", f, ignore.case=TRUE));
                        rmarkdown::render(f, output_format = "html_document", output_file = out, envir = new.env());
                      }'

      - name: Commit docs/
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add docs
          git diff --cached --quiet || git commit -m "Update docs (render Rmd)"
          git push
