name: Build R Site

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("rmarkdown","CCA","yacca","CCP","ggplot2","dplyr"), repos="https://cloud.r-project.org")'

      - name: Render R Markdown
        run: |
          mkdir -p docs
          Rscript -e 'rmarkdown::render("cca.Rmd", output_file = "../docs/cca.html")'
          Rscript -e 'rmarkdown::render("index.Rmd", output_file = "../docs/index.html")'

      - name: Add .nojekyll
        run: echo "" > docs/.nojekyll

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update site" || echo "No changes to commit"
          git push
