name: Render Rmd to docs (branch deploy)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install R packages (for 12 notebooks)
        run: |
          Rscript -e 'install.packages(c(
            "rmarkdown","knitr","prettydoc",
            "MASS","FactoMineR","factoextra",
            "nnet","e1071",
            "tidymodels","ranger"
          ))'

      - name: Ensure docs/ + theme + landing (optional)
        shell: bash
        run: |
          mkdir -p docs
          if [ ! -f docs/_config.yml ]; then
            cat > docs/_config.yml <<'YAML'
          title: Multivariate Analysis by R
          description: Showcase of multivariate methods generated from R notebooks
          remote_theme: pages-themes/cayman@v0.2.0
          plugins:
            - jekyll-remote-theme
          markdown: kramdown
          YAML
          fi
          if [ ! -f docs/index.md ]; then
            cat > docs/index.md <<'MD'
          ---
          layout: default
          ---
          # Multivariate Analysis by R
          Welcome! Click a method below.
          MD
          fi

      - name: Render ALL .Rmd (at repo root) into docs/
        run: |
          Rscript -e '
            dir.create("docs", showWarnings = FALSE)
            rmd_files <- list.files(".", pattern = "\\\\.Rmd$", full.names = TRUE)
            if (length(rmd_files) == 0) stop("No .Rmd files found in repo root")
            for (f in rmd_files) {
              out <- file.path("docs", paste0(tools::file_path_sans_ext(basename(f)), ".html"))
              message("Rendering: ", f, " -> ", out)
              tryCatch(
                rmarkdown::render(
                  f,
                  output_format = "prettydoc::html_pretty",
                  output_file   = out,
                  envir = new.env()
                ),
                error = function(e) { message("FAILED: ", f, " :: ", e$message); quit(status=1) }
              )
            }
          '

      - name: Show docs/
        run: ls -lah docs || true

      # Force-add phòng trường hợp còn rule ignore nào sót
      - name: Commit docs/
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add -f docs
          git diff --cached --quiet || git commit -m "Update docs (render Rmd)"
          git push
